using System.Collections.Frozen;
using System.Globalization;
using OopDesignChecker.Localization;

namespace OopDesignChecker.Gui;

internal enum GuiTextKey
{
    WindowTitle,
    LanguageLabel,
    TargetPlaceholder,
    ConfigurationPlaceholder,
    FileButton,
    FolderButton,
    ConfigurationButton,
    EditButton,
    ClearButton,
    AnalyzeButton,
    CancelButton,
    ShowLabel,
    Danger,
    Warning,
    Attention,
    SearchPlaceholder,
    CopySelectedButton,
    CopyAllButton,
    OpenSourceButton,
    ExportJsonButton,
    ExportSarifButton,
    Ready,
    SeverityColumn,
    RuleColumn,
    FileColumn,
    LineColumn,
    ColumnColumn,
    MessageColumn,
    DiagnosticDetails,
    SeverityDetail,
    RuleDetail,
    SymbolDetail,
    LocationDetail,
    SelectDiagnostic,
    TargetRequired,
    AnalysisCancelled,
    Cancelling,
    Completed,
    ConfigNotLoaded,
    ConfigDefaults,
    ConfigSummary,
    ChooseAnalysisTarget,
    CSharpTargetType,
    ChooseProjectDirectory,
    ChooseCheckerConfiguration,
    JsonConfigurationType,
    ConfigurationSaved,
    SaveCheckerConfiguration,
    RunBeforeExport,
    ExportDiagnosticsAs,
    DiagnosticsFileType,
    ExportedDiagnostics,
    ClipboardUnavailable,
    CopiedToClipboard,
    SourceNotFoundCopied,
    OpenedSource,
    CouldNotOpenCopied,
    Analyzing,
    EditorTitle,
    EditorDescription,
    ValidateButton,
    SaveButton,
    ConfigurationValid,
}

internal static class GuiText
{
    private static readonly FrozenDictionary<GuiTextKey, string> Japanese =
        new Dictionary<GuiTextKey, string>
        {
            [GuiTextKey.WindowTitle] = "OOP Design Checker",
            [GuiTextKey.LanguageLabel] = "言語:",
            [GuiTextKey.TargetPlaceholder] = "project / solution / C# file / project directory",
            [GuiTextKey.ConfigurationPlaceholder] = "任意: oop-design-checker.json",
            [GuiTextKey.FileButton] = "ファイル...",
            [GuiTextKey.FolderButton] = "フォルダー...",
            [GuiTextKey.ConfigurationButton] = "設定...",
            [GuiTextKey.EditButton] = "編集...",
            [GuiTextKey.ClearButton] = "クリア",
            [GuiTextKey.AnalyzeButton] = "解析",
            [GuiTextKey.CancelButton] = "キャンセル",
            [GuiTextKey.ShowLabel] = "表示:",
            [GuiTextKey.Danger] = "危険",
            [GuiTextKey.Warning] = "警告",
            [GuiTextKey.Attention] = "注意",
            [GuiTextKey.SearchPlaceholder] = "rule / file / symbol / messageで絞り込み",
            [GuiTextKey.CopySelectedButton] = "選択をコピー",
            [GuiTextKey.CopyAllButton] = "すべてコピー",
            [GuiTextKey.OpenSourceButton] = "sourceを開く",
            [GuiTextKey.ExportJsonButton] = "JSON出力...",
            [GuiTextKey.ExportSarifButton] = "SARIF出力...",
            [GuiTextKey.Ready] = "準備完了",
            [GuiTextKey.SeverityColumn] = "重大度",
            [GuiTextKey.RuleColumn] = "Rule",
            [GuiTextKey.FileColumn] = "File",
            [GuiTextKey.LineColumn] = "行",
            [GuiTextKey.ColumnColumn] = "列",
            [GuiTextKey.MessageColumn] = "Message",
            [GuiTextKey.DiagnosticDetails] = "診断詳細",
            [GuiTextKey.SeverityDetail] = "重大度: {0}",
            [GuiTextKey.RuleDetail] = "Rule: {0}",
            [GuiTextKey.SymbolDetail] = "Symbol: {0}",
            [GuiTextKey.LocationDetail] = "場所: {0}",
            [GuiTextKey.SelectDiagnostic] = "診断を選択すると詳細を表示します。",
            [GuiTextKey.TargetRequired] = "解析target pathを指定してください。",
            [GuiTextKey.AnalysisCancelled] = "解析をキャンセルしました。",
            [GuiTextKey.Cancelling] = "キャンセル中...",
            [GuiTextKey.Completed] = "完了: 診断 {0}件。",
            [GuiTextKey.ConfigNotLoaded] = "設定: 未読み込み",
            [GuiTextKey.ConfigDefaults] = "既定値",
            [GuiTextKey.ConfigSummary] = "設定: {0} | 失敗しきい値: {1} | 無効rule: {2} | 除外path: {3}",
            [GuiTextKey.ChooseAnalysisTarget] = "解析targetを選択",
            [GuiTextKey.CSharpTargetType] = "C# source / project / solution",
            [GuiTextKey.ChooseProjectDirectory] = "project directoryを選択",
            [GuiTextKey.ChooseCheckerConfiguration] = "checker設定を選択",
            [GuiTextKey.JsonConfigurationType] = "JSON設定",
            [GuiTextKey.ConfigurationSaved] = "設定を保存しました。再解析すると変更が反映されます。",
            [GuiTextKey.SaveCheckerConfiguration] = "checker設定を保存",
            [GuiTextKey.RunBeforeExport] = "診断をexportする前に解析を実行してください。",
            [GuiTextKey.ExportDiagnosticsAs] = "診断を{0}としてexport",
            [GuiTextKey.DiagnosticsFileType] = "{0}診断",
            [GuiTextKey.ExportedDiagnostics] = "診断を {0} へexportしました。",
            [GuiTextKey.ClipboardUnavailable] = "このplatformではclipboardを利用できません。",
            [GuiTextKey.CopiedToClipboard] = "clipboardへコピーしました。",
            [GuiTextKey.SourceNotFoundCopied] = "source fileが見つからないため、場所をコピーしました。",
            [GuiTextKey.OpenedSource] = "既定applicationでsource fileを開きました。",
            [GuiTextKey.CouldNotOpenCopied] = "source fileを開けなかったため、場所をコピーしました。",
            [GuiTextKey.Analyzing] = "解析中...",
            [GuiTextKey.EditorTitle] = "OOP Design Checker 設定",
            [GuiTextKey.EditorDescription] = "oop-design-checker.jsonを編集します。検証にはCUIと同じ設定modelを使用します。",
            [GuiTextKey.ValidateButton] = "検証",
            [GuiTextKey.SaveButton] = "保存",
            [GuiTextKey.ConfigurationValid] = "設定は有効です。",
        }.ToFrozenDictionary();

    private static readonly FrozenDictionary<GuiTextKey, string> English =
        new Dictionary<GuiTextKey, string>
        {
            [GuiTextKey.WindowTitle] = "OOP Design Checker",
            [GuiTextKey.LanguageLabel] = "Language:",
            [GuiTextKey.TargetPlaceholder] = "Project, solution, C# file, or project directory",
            [GuiTextKey.ConfigurationPlaceholder] = "Optional oop-design-checker.json",
            [GuiTextKey.FileButton] = "File...",
            [GuiTextKey.FolderButton] = "Folder...",
            [GuiTextKey.ConfigurationButton] = "Config...",
            [GuiTextKey.EditButton] = "Edit...",
            [GuiTextKey.ClearButton] = "Clear",
            [GuiTextKey.AnalyzeButton] = "Analyze",
            [GuiTextKey.CancelButton] = "Cancel",
            [GuiTextKey.ShowLabel] = "Show:",
            [GuiTextKey.Danger] = "Danger",
            [GuiTextKey.Warning] = "Warning",
            [GuiTextKey.Attention] = "Attention",
            [GuiTextKey.SearchPlaceholder] = "Filter by rule, file, symbol, or message",
            [GuiTextKey.CopySelectedButton] = "Copy selected",
            [GuiTextKey.CopyAllButton] = "Copy all",
            [GuiTextKey.OpenSourceButton] = "Open source",
            [GuiTextKey.ExportJsonButton] = "Export JSON...",
            [GuiTextKey.ExportSarifButton] = "Export SARIF...",
            [GuiTextKey.Ready] = "Ready",
            [GuiTextKey.SeverityColumn] = "Severity",
            [GuiTextKey.RuleColumn] = "Rule",
            [GuiTextKey.FileColumn] = "File",
            [GuiTextKey.LineColumn] = "Line",
            [GuiTextKey.ColumnColumn] = "Column",
            [GuiTextKey.MessageColumn] = "Message",
            [GuiTextKey.DiagnosticDetails] = "Diagnostic details",
            [GuiTextKey.SeverityDetail] = "Severity: {0}",
            [GuiTextKey.RuleDetail] = "Rule: {0}",
            [GuiTextKey.SymbolDetail] = "Symbol: {0}",
            [GuiTextKey.LocationDetail] = "Location: {0}",
            [GuiTextKey.SelectDiagnostic] = "Select a diagnostic to see its full message.",
            [GuiTextKey.TargetRequired] = "Target path is required.",
            [GuiTextKey.AnalysisCancelled] = "Analysis cancelled.",
            [GuiTextKey.Cancelling] = "Cancelling...",
            [GuiTextKey.Completed] = "Completed: {0} diagnostic(s).",
            [GuiTextKey.ConfigNotLoaded] = "Config: not loaded",
            [GuiTextKey.ConfigDefaults] = "defaults",
            [GuiTextKey.ConfigSummary] = "Config: {0} | Fail: {1} | Disabled: {2} | Ignored: {3}",
            [GuiTextKey.ChooseAnalysisTarget] = "Choose analysis target",
            [GuiTextKey.CSharpTargetType] = "C# source/project/solution",
            [GuiTextKey.ChooseProjectDirectory] = "Choose project directory",
            [GuiTextKey.ChooseCheckerConfiguration] = "Choose checker configuration",
            [GuiTextKey.JsonConfigurationType] = "JSON configuration",
            [GuiTextKey.ConfigurationSaved] = "Configuration saved. Analyze again to apply changes.",
            [GuiTextKey.SaveCheckerConfiguration] = "Save checker configuration",
            [GuiTextKey.RunBeforeExport] = "Run an analysis before exporting diagnostics.",
            [GuiTextKey.ExportDiagnosticsAs] = "Export diagnostics as {0}",
            [GuiTextKey.DiagnosticsFileType] = "{0} diagnostics",
            [GuiTextKey.ExportedDiagnostics] = "Exported diagnostics to {0}.",
            [GuiTextKey.ClipboardUnavailable] = "Clipboard is unavailable on this platform.",
            [GuiTextKey.CopiedToClipboard] = "Copied to clipboard.",
            [GuiTextKey.SourceNotFoundCopied] = "Source file was not found; location copied instead.",
            [GuiTextKey.OpenedSource] = "Opened source file with the default application.",
            [GuiTextKey.CouldNotOpenCopied] = "Could not open source file; location copied instead.",
            [GuiTextKey.Analyzing] = "Analyzing...",
            [GuiTextKey.EditorTitle] = "OOP Design Checker configuration",
            [GuiTextKey.EditorDescription] = "Edit oop-design-checker.json. Validation uses the same configuration model as the CUI.",
            [GuiTextKey.ValidateButton] = "Validate",
            [GuiTextKey.SaveButton] = "Save",
            [GuiTextKey.ConfigurationValid] = "Configuration is valid.",
        }.ToFrozenDictionary();

    public static string Get(GuiTextKey key, UserInterfaceLanguage language) =>
        language == UserInterfaceLanguage.Japanese ? Japanese[key] : English[key];

    public static string Format(
        GuiTextKey key,
        UserInterfaceLanguage language,
        params object?[] arguments
    ) => string.Format(CultureInfo.CurrentCulture, Get(key, language), arguments);
}
