<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>oop-design-checker-cui</AssemblyName>
    <RootNamespace>OopDesignChecker.Cui</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../OopDesignChecker/OopDesignChecker.csproj" />
  </ItemGroup>
</Project>
